const SEED_PLANT_LABOUR_PRELIM_SUPPLIERS = [
  {
    id: "supp-plant-julius-01",
    name: "Julius & Mikano Heavy Equipment & Plant Hire Ltd",
    category: "Plant & Equipment Hire",
    contactPerson: "Engr. Emeka Okonkwo",
    phone: "+234 803 319 8820",
    whatsapp: "+234 803 319 8820",
    email: "hire@mikanoplants.ng",
    address: "Kilometer 14, Lagos-Ibadan Expressway, Isheri North / Ikeja",
    state: "Lagos",
    coverageAreas: "Lagos, Ogun, Oyo, Abuja & Niger Delta",
    leadTime: "24 hours for mobilization",
    minOrder: "1 Day wet/dry lease",
    paymentTerms: "Mobilization advance + refundable deposit",
    verificationStatus: "Preferred Partner",
    rating: 4.9,
    notes: "Certified heavy earthmoving machinery with certified operators. Lowbed transporter mobilization available on short notice.",
    materials: [
      { name: "CAT 320 Hydraulic Excavator (20-Tonne, Wet Lease with Operator)", unit: "Day", rate: 22e4 },
      { name: "CAT D6 Track-Type Bulldozer (Wet Lease with Operator)", unit: "Day", rate: 26e4 },
      { name: "500-Litre Heavy Duty Diesel Reversing Concrete Mixer", unit: "Day", rate: 25e3 },
      { name: "Honda Engine Poker Vibrator with 5m Needle Hose", unit: "Day", rate: 12e3 },
      { name: "Bomag 10-Tonne Single Drum Vibratory Soil Compactor Roller", unit: "Day", rate: 165e3 },
      { name: "25-Tonne Tadano All-Terrain Mobile Telescopic Crane", unit: "Day", rate: 35e4 },
      { name: "100kVA Soundproof Perkins Diesel Site Generator", unit: "Day", rate: 45e3 }
    ]
  },
  {
    id: "supp-plant-tipper-02",
    name: "Direct Haulage & Heavy Tipper Operators Association",
    category: "Plant & Equipment Hire",
    contactPerson: "Alhaji Bashir Dantata",
    phone: "+234 805 601 4433",
    whatsapp: "+234 805 601 4433",
    email: "dispatch@directhaulage.ng",
    address: "Tipper Garage, Berger Junction, Utako, Abuja FCT",
    state: "Abuja (FCT)",
    coverageAreas: "Abuja FCT, Nasarawa, Kaduna, Niger State",
    leadTime: "Immediate dispatch / within 3 hours",
    minOrder: "1 Trip / Daily truck hire",
    paymentTerms: "Payment per trip or weekly invoice",
    verificationStatus: "Verified",
    rating: 4.8,
    notes: "Fleet of 6-wheeler and 10-wheeler Mack & Sinotruk tipper trucks for site excavation haulage, cart-away, granite and sand supply.",
    materials: [
      { name: "20-Tonne 10-Wheeler Tipper Truck (Day Hire for Site Cart-Away)", unit: "Day", rate: 95e3 },
      { name: "30-Tonne Semi-Trailer Tipper Truck (Bulk Haulage)", unit: "Day", rate: 14e4 },
      { name: "Excavation Cart-Away to Approved Dump Site (Urban Area)", unit: "Trip", rate: 35e3 },
      { name: "JCB Backhoe Loader (Excavator & Front Shovel)", unit: "Day", rate: 15e4 }
    ]
  },
  {
    id: "supp-labour-builders-01",
    name: "Lagos Master Craftsmen & Artisans Subcontracting Guild",
    category: "Labour & Subcontractors",
    contactPerson: "Bldr. Adeyemi Adeleke (FNIOB)",
    phone: "+234 802 334 1122",
    whatsapp: "+234 802 334 1122",
    email: "guild@lagoscraftsmen.org.ng",
    address: "Artisan Training Centre, Alausa CBD, Ikeja, Lagos",
    state: "Lagos",
    coverageAreas: "Lagos, Ogun, Oyo & Port Harcourt",
    leadTime: "48 hours for gang mobilization",
    minOrder: "1 Gang / Trade subcontract",
    paymentTerms: "Weekly measurement valuations or milestone draws",
    verificationStatus: "Preferred Partner",
    rating: 4.9,
    notes: "Trade-certified artisans vetted by the Nigerian Institute of Building (NIOB). PPE compliant, insured and supervised by qualified Trade Foremen.",
    materials: [
      { name: "Master Bricklayer / Mason Daily Wage", unit: "Day", rate: 12e3 },
      { name: "Iron Bender / Steel Fixer Daily Wage", unit: "Day", rate: 12500 },
      { name: "Formwork Structural Carpenter Daily Wage", unit: "Day", rate: 12e3 },
      { name: "General Construction Labourer / Assistant Daily Wage", unit: "Day", rate: 6e3 },
      { name: "Concrete Casting Gang (1 Mason + 1 Operator + 6 Labourers)", unit: "Day", rate: 58e3 },
      { name: "Blockwork Masonry Labour Rate (225mm Hollow Blocks)", unit: "m2", rate: 900 },
      { name: "Wall Plastering Labour Rate (Internal/External Plaster & Sponge)", unit: "m2", rate: 850 },
      { name: "Rebar Cutting, Bending & Fixing Labour Rate", unit: "Tonne", rate: 45e3 },
      { name: "Floor & Wall Tiling Labour Rate (Porcelain / Ceramic)", unit: "m2", rate: 1400 },
      { name: "POP Ceiling Suspension & Cornice Labour Rate", unit: "m2", rate: 1800 }
    ]
  },
  {
    id: "supp-labour-mep-02",
    name: "Apex MEP Engineering Artisans & Specialist Gangs",
    category: "Labour & Subcontractors",
    contactPerson: "Engr. Collins Chinedu",
    phone: "+234 803 772 9012",
    whatsapp: "+234 803 772 9012",
    email: "mep@apexartisans.ng",
    address: "12 Trans-Amadi Industrial Layout, Port Harcourt, Rivers",
    state: "Rivers",
    coverageAreas: "Port Harcourt, Yenagoa, Warri, Uyo, Owerri",
    leadTime: "24-48 hours",
    minOrder: "Phase milestone contract",
    paymentTerms: "First fix 40%, Second fix 40%, Commissioning 20%",
    verificationStatus: "Verified",
    rating: 4.8,
    notes: "Licensed electrical, plumbing, HVAC and firefighting technicians for high-end residential and commercial developments.",
    materials: [
      { name: "Licensed Plumber Daily Wage", unit: "Day", rate: 14e3 },
      { name: "Certified Industrial Electrician Daily Wage", unit: "Day", rate: 14e3 },
      { name: "Electrical Piping & Conduit Chasing Labour", unit: "Point", rate: 3500 },
      { name: "Sanitary Plumbing Drainage & Water Supply Piping", unit: "Point", rate: 5500 },
      { name: "Air Conditioner Piping & Trunking Installation", unit: "Unit", rate: 18e3 }
    ]
  },
  {
    id: "supp-prelim-scaffold-01",
    name: "Sure-Access Scaffolding & Site Logistics Ltd",
    category: "Preliminaries & Site Services",
    contactPerson: "Engr. Babatunde Fashanu",
    phone: "+234 809 112 5566",
    whatsapp: "+234 809 112 5566",
    email: "operations@sureaccess.ng",
    address: "Km 23 Lekki-Epe Expressway, Ajah, Lagos",
    state: "Lagos",
    coverageAreas: "South West & Nationwide",
    leadTime: "24 hours mobilization & rigging",
    minOrder: "1 Set / 200m2 facade",
    paymentTerms: "Monthly advance rental + rigging fee",
    verificationStatus: "Preferred Partner",
    rating: 4.9,
    notes: "BS EN 12811 certified galvanised steel quickstage scaffolding sets, base plates, standards, ledgers, metal planks, safety catch nets and certified erectors.",
    materials: [
      { name: "Tubular Steel Scaffolding Complete System (Monthly Hire)", unit: "m2", rate: 1800 },
      { name: "Mobile Aluminium Mobile Tower Scaffolding (10m Height)", unit: "Week", rate: 65e3 },
      { name: "Scaffolding Erection, Inspection Tagging & Dismantling", unit: "m2", rate: 650 },
      { name: "Perimeter Safety Debris Catch Netting", unit: "m2", rate: 450 }
    ]
  },
  {
    id: "supp-prelim-sitecabins-02",
    name: "Apex Mobile Site Cabins, Borehole & Temporary Works",
    category: "Preliminaries & Site Services",
    contactPerson: "Arc. Sani Bello",
    phone: "+234 802 990 3311",
    whatsapp: "+234 802 990 3311",
    email: "sitefacilities@apexcabins.ng",
    address: "Plot 104 Idu Industrial Area Phase 2, Abuja FCT",
    state: "Abuja (FCT)",
    coverageAreas: "Abuja, Niger, Plateau, Kaduna & Kano",
    leadTime: "48 hours delivery & crane offload",
    minOrder: "1 Month lease",
    paymentTerms: "Monthly in advance",
    verificationStatus: "Verified",
    rating: 4.8,
    notes: "Turnkey site establishment facilities: Insulated container site offices with AC, lockable material storage containers, industrial borehole drilling, and mobile chemical toilets.",
    materials: [
      { name: "20ft Insulated Container Site Office with AC & Wiring (Rental)", unit: "Month", rate: 18e4 },
      { name: "20ft Secure Steel Shipping Container for Material Storage", unit: "Month", rate: 12e4 },
      { name: "Deep Industrial Site Borehole Drilling & Submersible Pump Rig", unit: "Item", rate: 125e4 },
      { name: "Portable Chemical Site Toilet Unit (Monthly Hire with Servicing)", unit: "Month", rate: 75e3 },
      { name: "Standard Project Signboard (2400 x 1800mm High Reflective Steel)", unit: "Item", rate: 185e3 },
      { name: "Corrugated Zinc Site Perimeter Hoarding & Timber Posts", unit: "m", rate: 8500 },
      { name: "5000-Litre Clean Construction Water Delivery Bowser", unit: "Trip", rate: 25e3 },
      { name: "Topographical Site Survey & Setting Out by Registered Surveyor", unit: "Item", rate: 35e4 }
    ]
  },
  {
    id: "supp-plant-ph-marine-03",
    name: "Niger Delta Marine & Swamp Heavy Plant Hire Ltd",
    category: "Plant & Equipment Hire",
    contactPerson: "Engr. Tariye Briggs",
    phone: "+234 803 550 9182",
    whatsapp: "+234 803 550 9182",
    email: "hire@nigerdeltaplant.ng",
    address: "Trans-Amadi Industrial Layout, Port Harcourt, Rivers State",
    state: "Rivers",
    coverageAreas: "Port Harcourt, Yenagoa, Warri, Bonny Island, Calabar",
    leadTime: "24 hours mobilization",
    minOrder: "1 Day wet/dry lease",
    paymentTerms: "Mobilization advance + insurance bond",
    verificationStatus: "Preferred Partner",
    rating: 4.9,
    notes: "Specialized swamp and Niger Delta heavy earthmoving equipment: Amphibious swamp buggies, long-reach marsh excavators, rotary bored piling rigs, and tug barge logistics.",
    materials: [
      { name: "Amphibious Swamp Buggy Excavator (Wet Lease with Operator)", unit: "Day", rate: 42e4 },
      { name: "Rotary Bored Piling Rig (600mm-1200mm diameter)", unit: "Day", rate: 65e4 },
      { name: "50-Tonne Crawler Crane for Swamp & Heavy Piling", unit: "Day", rate: 48e4 },
      { name: "Sheet Pile Driving Vibratory Hammer Rig", unit: "Day", rate: 38e4 },
      { name: "Flat Deck Cargo Tug Barge (500-Tonne Capacity)", unit: "Day", rate: 55e4 },
      { name: "4-Inch High-Volume Trash Dewatering Pump", unit: "Day", rate: 28e3 }
    ]
  },
  {
    id: "supp-labour-ph-welders-03",
    name: "Port Harcourt Certified Steel Fabricators & Marine Artisans Guild",
    category: "Labour & Subcontractors",
    contactPerson: "Chief Tamuno George (QS)",
    phone: "+234 802 441 7890",
    whatsapp: "+234 802 441 7890",
    email: "guild@phmarineartisans.ng",
    address: "Abonnema Wharf Road, Port Harcourt, Rivers State",
    state: "Rivers",
    coverageAreas: "Rivers, Bayelsa, Delta, Akwa Ibom",
    leadTime: "48 hours for gang mobilization",
    minOrder: "1 Subcontract package",
    paymentTerms: "Milestone draw / weekly measurement",
    verificationStatus: "Preferred Partner",
    rating: 4.9,
    notes: "Coded 6G ASME certified pipe welders, structural steel erectors, heavy rigging crews, marine pile shuttering carpenters and concrete gangs.",
    materials: [
      { name: "Certified 6G Pipe & Structural Welder Daily Wage", unit: "Day", rate: 18e3 },
      { name: "Heavy Structural Steel Erector / Rigging Specialist", unit: "Day", rate: 15e3 },
      { name: "Underwater / Marine Timber Piling Specialist Carpenter", unit: "Day", rate: 16500 },
      { name: "Structural Steel Fabrication Labour Rate", unit: "Tonne", rate: 85e3 },
      { name: "Heavy Pile Cap Shuttering & Striking Gang (Day Rate)", unit: "Day", rate: 65e3 }
    ]
  },
  {
    id: "supp-plant-kano-north-04",
    name: "Sahel Heavy Earthmovers & Mobile Crushing Equipment Ltd",
    category: "Plant & Equipment Hire",
    contactPerson: "Alhaji Mansur Garba",
    phone: "+234 806 882 3341",
    whatsapp: "+234 806 882 3341",
    email: "sahelplants@kano-earthmovers.ng",
    address: "Bompai Industrial Area, Kano & Kaduna Highway Corridor",
    state: "Kano",
    coverageAreas: "Kano, Kaduna, Jigawa, Katsina, Abuja FCT",
    leadTime: "24 hours",
    minOrder: "1 Day wet lease",
    paymentTerms: "Payment on mobilization",
    verificationStatus: "Verified",
    rating: 4.8,
    notes: "Earthmoving and road construction machinery fleet across Kano, Kaduna, and Abuja corridor. GPS-guided level sensors on graders.",
    materials: [
      { name: "CAT 140K Motor Grader with GPS Level Sensor", unit: "Day", rate: 24e4 },
      { name: "15-Tonne Pneumatic Road Roller Compactor", unit: "Day", rate: 175e3 },
      { name: "Wheel Loader (3.0m\xB3 Bucket Capacity)", unit: "Day", rate: 195e3 },
      { name: "Mobile Tracked Jaw Stone Crusher", unit: "Day", rate: 58e4 },
      { name: "10,000L Water Tanker Truck for Earth Compaction", unit: "Day", rate: 65e3 }
    ]
  },
  {
    id: "supp-prelim-ph-environ-03",
    name: "Niger Delta Swamp Site Preliminaries, Environmental & Safety Services",
    category: "Preliminaries & Site Services",
    contactPerson: "Engr. Nnamdi Amadi",
    phone: "+234 803 711 0022",
    whatsapp: "+234 803 711 0022",
    email: "safety@deltasiteservices.ng",
    address: "Peter Odili Road, Trans-Amadi, Port Harcourt, Rivers State",
    state: "Rivers",
    coverageAreas: "Rivers, Bayelsa, Delta, Imo",
    leadTime: "24-48 hours",
    minOrder: "Monthly package",
    paymentTerms: "Advance monthly rental",
    verificationStatus: "Preferred Partner",
    rating: 4.8,
    notes: "Specialist swamp establishment: Swamp board walks, safety rescue boats, containment booms, heavy duty wellpoint dewatering sets, and environmental safety.",
    materials: [
      { name: "High-Capacity Wellpoint Dewatering System Complete Set (Monthly Hire)", unit: "Month", rate: 85e4 },
      { name: "Heavy Duty Swamp Boardwalk / Timber Mat Roadway", unit: "m", rate: 22e3 },
      { name: "Site Safety Patrol Boat with 40HP Yamaha Outboard (Monthly Hire)", unit: "Month", rate: 35e4 },
      { name: "Oil-Water Separation Interceptor Trap", unit: "Item", rate: 42e4 },
      { name: "Site Medical First Aid Station & Paramedic Crew", unit: "Month", rate: 28e4 }
    ]
  }
];
const DEFAULT_LIBRARY_RATES = [
  // --- MATERIALS ---
  {
    id: "rate-mat-01",
    type: "Material",
    category: "Cement & Aggregates",
    item: "Grade 42.5R Ordinary Portland Cement (50kg bag)",
    specification: "High early strength CEM I / 42.5R (Dangote / BUA / Lafarge Supaset)",
    unit: "Bag",
    lagosRate: 9500,
    abujaRate: 9800,
    portHarcourtRate: 9300,
    northernRate: 9200,
    materialComponent: 9500,
    labourComponent: 0,
    plantComponent: 0,
    overheadProfitPercent: 10,
    trend: "up",
    trendPercent: 2.1,
    keySuppliers: ["Dangote Cement Depot", "BUA Cement Depot", "Lafarge Retail"]
  },
  {
    id: "rate-mat-02",
    type: "Material",
    category: "Cement & Aggregates",
    item: "Clean Sharp River Sand (Concrete Aggregate)",
    specification: "Clean coarse riverbed sand, free of silt and organic clay minerals",
    unit: "Tonne",
    lagosRate: 6500,
    abujaRate: 7200,
    portHarcourtRate: 8500,
    northernRate: 5500,
    materialComponent: 6500,
    labourComponent: 0,
    plantComponent: 0,
    overheadProfitPercent: 10,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Epe Dredging Depot", "Mpape River Sand", "Choba Dredgers PH"]
  },
  {
    id: "rate-mat-03",
    type: "Material",
    category: "Cement & Aggregates",
    item: 'Crushed Blue Granite 20mm (3/4" Aggregates)',
    specification: "Machine-crushed angular igneous granite aggregate for structural concrete",
    unit: "Tonne",
    lagosRate: 11500,
    abujaRate: 12e3,
    portHarcourtRate: 14500,
    northernRate: 9800,
    materialComponent: 11500,
    labourComponent: 0,
    plantComponent: 0,
    overheadProfitPercent: 10,
    trend: "up",
    trendPercent: 1.5,
    keySuppliers: ["Royal Quarries Abeokuta", "Julius Berger Quarry Abuja", "Akamkpa Quarries Calabar"]
  },
  {
    id: "rate-mat-04",
    type: "Material",
    category: "Steel & Rebar",
    item: "High-Yield TMT Steel Rebars Y12 (12m Length)",
    specification: "Thermo-Mechanically Treated ribbed deformed rebar fy >= 460 N/mm\xB2",
    unit: "Tonne",
    lagosRate: 143e4,
    abujaRate: 148e4,
    portHarcourtRate: 152e4,
    northernRate: 149e4,
    materialComponent: 143e4,
    labourComponent: 0,
    plantComponent: 0,
    overheadProfitPercent: 8,
    trend: "down",
    trendPercent: 1.8,
    keySuppliers: ["Pulkit Steel Mills", "African Foundries", "Tiger TMT"]
  },
  {
    id: "rate-mat-05",
    type: "Material",
    category: "Steel & Rebar",
    item: "High-Yield TMT Steel Rebars Y16 (12m Length)",
    specification: "Standard structural beam and column rebar fy >= 460 N/mm\xB2",
    unit: "Tonne",
    lagosRate: 142e4,
    abujaRate: 147e4,
    portHarcourtRate: 151e4,
    northernRate: 148e4,
    materialComponent: 142e4,
    labourComponent: 0,
    plantComponent: 0,
    overheadProfitPercent: 8,
    trend: "down",
    trendPercent: 1.5,
    keySuppliers: ["Pulkit Steel Mills", "African Foundries", "Tiger TMT"]
  },
  {
    id: "rate-mat-06",
    type: "Material",
    category: "Blocks & Masonry",
    item: "9-inch (225mm) Vibrated Hollow Sandcrete Block",
    specification: "NIS 87:2000 compliant machine-vibrated blocks cured 14 days, crushing strength >= 3.45 N/mm\xB2",
    unit: "Unit",
    lagosRate: 600,
    abujaRate: 650,
    portHarcourtRate: 700,
    northernRate: 550,
    materialComponent: 600,
    labourComponent: 0,
    plantComponent: 0,
    overheadProfitPercent: 10,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Vibro-Cast Sandcrete Blocks", "Solid Rock Blocks", "Abuja Block Hub"]
  },
  {
    id: "rate-mat-07",
    type: "Material",
    category: "Roofing & Cladding",
    item: "0.55mm Thickness Aluminium Longspan Roofing Sheet",
    specification: "Alloy 3004/3105 baked enamel oven-cured coil, continuous roll-formed",
    unit: "m2",
    lagosRate: 7500,
    abujaRate: 8e3,
    portHarcourtRate: 7800,
    northernRate: 7600,
    materialComponent: 7500,
    labourComponent: 0,
    plantComponent: 0,
    overheadProfitPercent: 10,
    trend: "up",
    trendPercent: 3.2,
    keySuppliers: ["Topfeathers Aluminium", "Tower Aluminium Rolling", "MIDAS Metals"]
  },
  {
    id: "rate-mat-08",
    type: "Material",
    category: "Timber & Formwork",
    item: '2" x 4" x 12ft Hardwood Structural Timber',
    specification: "Seasoned Nigerian hardwood (Obeche/Mahogany/Opepe) straight-sawn",
    unit: "Piece",
    lagosRate: 2450,
    abujaRate: 2700,
    portHarcourtRate: 2600,
    northernRate: 2500,
    materialComponent: 2450,
    labourComponent: 0,
    plantComponent: 0,
    overheadProfitPercent: 10,
    trend: "stable",
    trendPercent: 0.5,
    keySuppliers: ["Mambilla & Sapele Hardwood Timber Concession", "Oko-Baba Timber Market"]
  },
  {
    id: "rate-mat-09",
    type: "Material",
    category: "Timber & Formwork",
    item: '1" x 12" x 12ft Black Marine Board Plywood (Formwork)',
    specification: "18mm Phenolic film-faced WBP waterproof shuttering plywood board",
    unit: "Sheet",
    lagosRate: 18500,
    abujaRate: 19500,
    portHarcourtRate: 19e3,
    northernRate: 18800,
    materialComponent: 18500,
    labourComponent: 0,
    plantComponent: 0,
    overheadProfitPercent: 10,
    trend: "up",
    trendPercent: 1.2,
    keySuppliers: ["Mambilla & Sapele Hardwood Timber Concession", "Alaba Plywood Hub"]
  },
  {
    id: "rate-mat-10",
    type: "Material",
    category: "Finishing & Tiles",
    item: "600x600mm Vitrified Porcelain Floor Tiles",
    specification: "First choice nano-polished glazed vitrified porcelain tiles",
    unit: "m2",
    lagosRate: 8500,
    abujaRate: 9200,
    portHarcourtRate: 9e3,
    northernRate: 8800,
    materialComponent: 8500,
    labourComponent: 0,
    plantComponent: 0,
    overheadProfitPercent: 10,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Time Ceramics Nigeria", "Golden Crown Tiles", "C-Don Tiles Depot"]
  },
  // --- PLANTS & HEAVY EQUIPMENT HIRE ---
  {
    id: "rate-plant-01",
    type: "Plant",
    category: "Heavy Earthmoving",
    item: "CAT 320 Hydraulic Excavator (20-Tonne) Wet Lease",
    specification: "20-Tonne crawler excavator with 1.0m3 bucket, wet lease includes operator & daily maintenance",
    unit: "Day",
    lagosRate: 22e4,
    abujaRate: 24e4,
    portHarcourtRate: 25e4,
    northernRate: 21e4,
    materialComponent: 45e3,
    // fuel & grease
    labourComponent: 25e3,
    // operator wage
    plantComponent: 15e4,
    // machine net rental
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Julius & Mikano Heavy Equipment & Plant Hire", "Direct Haulage"]
  },
  {
    id: "rate-plant-02",
    type: "Plant",
    category: "Heavy Earthmoving",
    item: "CAT D6 Track-Type Bulldozer Wet Lease",
    specification: "165 HP crawler bulldozer with semi-U blade and multi-shank ripper for site clearance & cut/fill",
    unit: "Day",
    lagosRate: 26e4,
    abujaRate: 28e4,
    portHarcourtRate: 29e4,
    northernRate: 25e4,
    materialComponent: 55e3,
    labourComponent: 25e3,
    plantComponent: 18e4,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Julius & Mikano Heavy Equipment & Plant Hire", "Dantata Plant Fleet"]
  },
  {
    id: "rate-plant-03",
    type: "Plant",
    category: "Concrete Equipment",
    item: "500-Litre Heavy Duty Diesel Reversing Concrete Mixer",
    specification: "500/350L mechanical hopper batch mixer with Petter/Lister diesel engine",
    unit: "Day",
    lagosRate: 25e3,
    abujaRate: 28e3,
    portHarcourtRate: 3e4,
    northernRate: 24e3,
    materialComponent: 8e3,
    // diesel
    labourComponent: 4e3,
    // operator assistant
    plantComponent: 13e3,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Julius & Mikano Heavy Equipment & Plant Hire", "Local Plant Pools"]
  },
  {
    id: "rate-plant-04",
    type: "Plant",
    category: "Concrete Equipment",
    item: "High-Frequency Petrol Poker Vibrator with 5m Needle",
    specification: "5.5 HP Honda engine mechanical poker vibrator with 38mm/45mm poker needle hose",
    unit: "Day",
    lagosRate: 12e3,
    abujaRate: 14e3,
    portHarcourtRate: 15e3,
    northernRate: 12e3,
    materialComponent: 4e3,
    labourComponent: 2e3,
    plantComponent: 6e3,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Julius & Mikano Heavy Equipment & Plant Hire", "Sure-Tool Hire"]
  },
  {
    id: "rate-plant-05",
    type: "Plant",
    category: "Haulage & Trucks",
    item: "20-Tonne 10-Wheeler Tipper Truck (Day Hire)",
    specification: "Sinotruk/Mack 10-wheeler tipper truck for onsite excavation haulage and spoil cart-away",
    unit: "Day",
    lagosRate: 95e3,
    abujaRate: 105e3,
    portHarcourtRate: 11e4,
    northernRate: 9e4,
    materialComponent: 3e4,
    labourComponent: 15e3,
    plantComponent: 5e4,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Direct Haulage & Heavy Tipper Operators", "Lekki Tipper Yard"]
  },
  {
    id: "rate-plant-06",
    type: "Plant",
    category: "Compaction & Rollers",
    item: "Bomag 10-Tonne Single Drum Vibratory Soil Compactor",
    specification: "10-Tonne self-propelled vibratory smooth drum roller for subgrade and hardcore compaction",
    unit: "Day",
    lagosRate: 165e3,
    abujaRate: 18e4,
    portHarcourtRate: 19e4,
    northernRate: 16e4,
    materialComponent: 35e3,
    labourComponent: 2e4,
    plantComponent: 11e4,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Julius & Mikano Heavy Equipment & Plant Hire"]
  },
  {
    id: "rate-plant-07",
    type: "Plant",
    category: "Lifting & Cranes",
    item: "25-Tonne Tadano All-Terrain Mobile Telescopic Crane",
    specification: "Hydraulic truck crane with 31m telescopic boom for precast lifting and structural steel erection",
    unit: "Day",
    lagosRate: 35e4,
    abujaRate: 38e4,
    portHarcourtRate: 4e5,
    northernRate: 34e4,
    materialComponent: 6e4,
    labourComponent: 4e4,
    plantComponent: 25e4,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Julius & Mikano Heavy Equipment & Plant Hire", "Cranes Nigeria Ltd"]
  },
  {
    id: "rate-plant-08",
    type: "Plant",
    category: "Site Power & Utilities",
    item: "100kVA Soundproof Perkins Diesel Site Generator",
    specification: "Prime-rated 100kVA 3-phase generator for tower cranes, concrete batching, and site welding",
    unit: "Day",
    lagosRate: 45e3,
    abujaRate: 5e4,
    portHarcourtRate: 52e3,
    northernRate: 44e3,
    materialComponent: 15e3,
    labourComponent: 5e3,
    plantComponent: 25e3,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Julius & Mikano Heavy Equipment & Plant Hire", "PowerPro Hire"]
  },
  // --- LABOUR & ARTISAN GANGS ---
  {
    id: "rate-lab-01",
    type: "Labour",
    category: "Masonry & Blockwork",
    item: "Master Bricklayer / Mason Daily Wage",
    specification: "Qualified blocklayer setting out alignment, plumb lines, mortar bedding and pointing",
    unit: "Day",
    lagosRate: 12e3,
    abujaRate: 13e3,
    portHarcourtRate: 13500,
    northernRate: 1e4,
    materialComponent: 0,
    labourComponent: 12e3,
    plantComponent: 0,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Lagos Master Craftsmen & Artisans Subcontracting Guild"]
  },
  {
    id: "rate-lab-02",
    type: "Labour",
    category: "Steel Fixing & Reinforcement",
    item: "Iron Bender / Steel Fixer Daily Wage",
    specification: "Certified steel fixer cutting, bending hooks, cranks, and tying high-yield rebars with binding wire",
    unit: "Day",
    lagosRate: 12500,
    abujaRate: 13500,
    portHarcourtRate: 14e3,
    northernRate: 10500,
    materialComponent: 0,
    labourComponent: 12500,
    plantComponent: 0,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Lagos Master Craftsmen & Artisans Subcontracting Guild"]
  },
  {
    id: "rate-lab-03",
    type: "Labour",
    category: "Carpentry & Formwork",
    item: "Formwork Structural Carpenter Daily Wage",
    specification: "Skilled shuttering carpenter fabricating timber/plywood forms, props, bracing, and striking",
    unit: "Day",
    lagosRate: 12e3,
    abujaRate: 13e3,
    portHarcourtRate: 13500,
    northernRate: 1e4,
    materialComponent: 0,
    labourComponent: 12e3,
    plantComponent: 0,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Lagos Master Craftsmen & Artisans Subcontracting Guild"]
  },
  {
    id: "rate-lab-04",
    type: "Labour",
    category: "General Site Workforce",
    item: "General Construction Labourer / Assistant Daily Wage",
    specification: "Unskilled site operative for manual excavation, aggregate haulage, concrete wheeling and site tidiness",
    unit: "Day",
    lagosRate: 6e3,
    abujaRate: 6500,
    portHarcourtRate: 7e3,
    northernRate: 5e3,
    materialComponent: 0,
    labourComponent: 6e3,
    plantComponent: 0,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Lagos Master Craftsmen & Artisans Subcontracting Guild"]
  },
  {
    id: "rate-lab-05",
    type: "Labour",
    category: "Concrete & Concreting",
    item: "Concrete Casting Gang (1 Mason + 1 Operator + 6 Labourers)",
    specification: "Full batch casting gang: mixing, transporting, pouring, vibrator compaction, and screeding",
    unit: "Day",
    lagosRate: 58e3,
    abujaRate: 64e3,
    portHarcourtRate: 66e3,
    northernRate: 52e3,
    materialComponent: 0,
    labourComponent: 58e3,
    plantComponent: 0,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Lagos Master Craftsmen & Artisans Subcontracting Guild"]
  },
  {
    id: "rate-lab-06",
    type: "Labour",
    category: "Masonry & Blockwork",
    item: "225mm Blockwork Masonry Labour Rate",
    specification: 'Laying 225mm (9") vibrated hollow sandcrete blocks in cement-sand (1:4) mortar complete with jointing',
    unit: "m2",
    lagosRate: 900,
    abujaRate: 950,
    portHarcourtRate: 1050,
    northernRate: 800,
    materialComponent: 0,
    labourComponent: 900,
    plantComponent: 0,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Lagos Master Craftsmen & Artisans Subcontracting Guild"]
  },
  {
    id: "rate-lab-07",
    type: "Labour",
    category: "Plastering & Rendering",
    item: "Wall Plastering & Sponge Finish Labour Rate",
    specification: "15mm thick cement-sand (1:4) internal plastering floated smooth and wood-floated or sponged finish",
    unit: "m2",
    lagosRate: 850,
    abujaRate: 900,
    portHarcourtRate: 1e3,
    northernRate: 750,
    materialComponent: 0,
    labourComponent: 850,
    plantComponent: 0,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Lagos Master Craftsmen & Artisans Subcontracting Guild"]
  },
  {
    id: "rate-lab-08",
    type: "Labour",
    category: "Steel Fixing & Reinforcement",
    item: "Rebar Cutting, Bending & Fixing Labour Rate",
    specification: "Unloading, cutting, bending to BS 8666 bar schedule, and tying high-yield rebars in foundations & slabs",
    unit: "Tonne",
    lagosRate: 45e3,
    abujaRate: 48e3,
    portHarcourtRate: 52e3,
    northernRate: 4e4,
    materialComponent: 0,
    labourComponent: 45e3,
    plantComponent: 0,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Lagos Master Craftsmen & Artisans Subcontracting Guild"]
  },
  {
    id: "rate-lab-09",
    type: "Labour",
    category: "Tiling & Flooring",
    item: "Floor & Wall Porcelain Tiling Labour Rate",
    specification: "Laying 600x600mm porcelain tiles on prepared screed with adhesive, spacers, and antimicrobial grout",
    unit: "m2",
    lagosRate: 1400,
    abujaRate: 1500,
    portHarcourtRate: 1650,
    northernRate: 1300,
    materialComponent: 0,
    labourComponent: 1400,
    plantComponent: 0,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Lagos Master Craftsmen & Artisans Subcontracting Guild"]
  },
  {
    id: "rate-lab-10",
    type: "Labour",
    category: "MEP Trades",
    item: "Licensed Industrial Electrician Daily Wage",
    specification: "Certified electrician for conduits, cable pulling, distribution board wiring, and earthing installation",
    unit: "Day",
    lagosRate: 14e3,
    abujaRate: 15e3,
    portHarcourtRate: 15500,
    northernRate: 12e3,
    materialComponent: 0,
    labourComponent: 14e3,
    plantComponent: 0,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Apex MEP Engineering Artisans & Specialist Gangs"]
  },
  // --- PRELIMINARIES & SITE SERVICES ---
  {
    id: "rate-pre-01",
    type: "Preliminaries",
    category: "Scaffolding & Access",
    item: "Tubular Steel Scaffolding Complete System (Monthly Hire)",
    specification: "Galvanised steel quickstage scaffolding frame, cross-braces, metal walk boards, base jacks, and toe boards",
    unit: "m2/Month",
    lagosRate: 1800,
    abujaRate: 2e3,
    portHarcourtRate: 2100,
    northernRate: 1700,
    materialComponent: 0,
    labourComponent: 300,
    // inspection
    plantComponent: 1500,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Sure-Access Scaffolding & Site Logistics Ltd"]
  },
  {
    id: "rate-pre-02",
    type: "Preliminaries",
    category: "Site Establishment & Accommodation",
    item: "20ft Insulated Container Site Office with AC (Rental)",
    specification: "Standard 20ft marine container converted to site office with EPS insulation, AC, lighting, sockets & desk",
    unit: "Month",
    lagosRate: 18e4,
    abujaRate: 195e3,
    portHarcourtRate: 21e4,
    northernRate: 175e3,
    materialComponent: 2e4,
    labourComponent: 1e4,
    plantComponent: 15e4,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Apex Mobile Site Cabins, Borehole & Temporary Works"]
  },
  {
    id: "rate-pre-03",
    type: "Preliminaries",
    category: "Site Establishment & Accommodation",
    item: "20ft Secure Steel Shipping Container for Material Storage",
    specification: "Heavy-duty corten steel weatherproof storage container with secure lockbox for cement & tools",
    unit: "Month",
    lagosRate: 12e4,
    abujaRate: 13e4,
    portHarcourtRate: 14e4,
    northernRate: 115e3,
    materialComponent: 1e4,
    labourComponent: 5e3,
    plantComponent: 105e3,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Apex Mobile Site Cabins, Borehole & Temporary Works"]
  },
  {
    id: "rate-pre-04",
    type: "Preliminaries",
    category: "Temporary Utilities & Water",
    item: "Deep Industrial Site Borehole Drilling & Submersible Pump Rig",
    specification: "Drilling 80m-120m deep borehole, PVC casing, gravel pack, 1.5HP submersible pump, and basic surface tap",
    unit: "Item",
    lagosRate: 125e4,
    abujaRate: 135e4,
    portHarcourtRate: 14e5,
    northernRate: 115e4,
    materialComponent: 55e4,
    labourComponent: 25e4,
    plantComponent: 45e4,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Apex Mobile Site Cabins, Borehole & Temporary Works"]
  },
  {
    id: "rate-pre-05",
    type: "Preliminaries",
    category: "Health, Safety & Sanitation",
    item: "Portable Chemical Site Toilet Unit (Monthly Hire with Servicing)",
    specification: "Recirculating chemical flush portable toilet cabin with weekly suction pump servicing and deodorizer",
    unit: "Month",
    lagosRate: 75e3,
    abujaRate: 85e3,
    portHarcourtRate: 9e4,
    northernRate: 7e4,
    materialComponent: 25e3,
    // chemicals
    labourComponent: 2e4,
    // servicing
    plantComponent: 3e4,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Apex Mobile Site Cabins, Borehole & Temporary Works"]
  },
  {
    id: "rate-pre-06",
    type: "Preliminaries",
    category: "Site Security & Hoarding",
    item: "Corrugated Zinc Site Perimeter Hoarding & Timber Posts",
    specification: "2.4m high corrugated galvanised zinc sheet hoarding on 75x75mm hardwood posts at 1.8m centers",
    unit: "m",
    lagosRate: 8500,
    abujaRate: 9200,
    portHarcourtRate: 9800,
    northernRate: 8e3,
    materialComponent: 6e3,
    labourComponent: 2e3,
    plantComponent: 500,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Apex Mobile Site Cabins, Borehole & Temporary Works"]
  },
  {
    id: "rate-pre-07",
    type: "Preliminaries",
    category: "Statutory & Administrative",
    item: "Standard Project Signboard (2400 x 1800mm High Reflective Steel)",
    specification: "Statutory project display board listing Client, Architect, Structural Engr, QS, MEP & Main Contractor",
    unit: "Item",
    lagosRate: 185e3,
    abujaRate: 2e5,
    portHarcourtRate: 21e4,
    northernRate: 175e3,
    materialComponent: 12e4,
    labourComponent: 45e3,
    plantComponent: 2e4,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Apex Mobile Site Cabins, Borehole & Temporary Works"]
  },
  {
    id: "rate-pre-08",
    type: "Preliminaries",
    category: "Surveys & Setting Out",
    item: "Topographical Site Survey & Setting Out by Registered Surveyor",
    specification: "Establishing site grid, benchmark datum levels, boundary coordinates, and structural axis pegs",
    unit: "Item",
    lagosRate: 35e4,
    abujaRate: 38e4,
    portHarcourtRate: 4e5,
    northernRate: 32e4,
    materialComponent: 5e4,
    labourComponent: 22e4,
    plantComponent: 8e4,
    overheadProfitPercent: 15,
    trend: "stable",
    trendPercent: 0,
    keySuppliers: ["Apex Mobile Site Cabins, Borehole & Temporary Works"]
  }
];
export {
  DEFAULT_LIBRARY_RATES,
  SEED_PLANT_LABOUR_PRELIM_SUPPLIERS
};
